# import = ["~/.config/alacritty/themes/noctalia.toml"]

general.import = [ "./one-dark.toml", "./font.toml" ]

[window]
padding = { x = 15, y = 15 }
decorations = "None"
opacity = 1
blur = false

[cursor]
# style = { shape = "Bar", blinking = "Always" } 
blink_interval = 550
