listener {
  timeout = 600  # 10 minutes
  on-timeout = qs -c noctalia-shell ipc call lockScreen lock
}

listener {
  timeout = 300 # 5 minutes
  on-timeout = brightnessctl -s set 1%
  on-resume = brightnessctl -r
}

