# Variables
$mainMod = ALT_R # Sets "Left Alt" key as main modifier
$shiftMod = SHIFT $mainMod
$ctrlShift = CONTROL_R SHIFT
$superShift = SUPERSHIFT
$windowsKey = SUPER_L

# Dispatchers
bind = $shiftMod, Q, killactive,
bind = $shiftMod, SPACE, exec, ~/.config/hypr/scripts/toggleFloating.sh
bind = $mainMod, F, fullscreen, 0
bind = $windowsKey, J, layoutmsg, togglesplit

# Programs
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, W, exec, $menu
bind = $mainMod, P, exec, $powerMenu
bind = $mainMod, M, exec, $displayMenu
bind = $mainMod, S, exec, hyprshot -m region --clipboard-only -s

# Noctalia
# bind = , $windowsKey, exec, $ipc controlCenter toggle
bind = $mainMod, N, exec, $ipc wallpaper toggle
# bind = $mainMod, P, pseudo, # dwindle
# bind = ALT_R, TAB, exec, $ipc launcher windows

# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Swap window
bind = $shiftMod, H, swapwindow, l
bind = $shiftMod, L, swapwindow, r
bind = $shiftMod, K, swapwindow, u
bind = $shiftMod, J, swapwindow, d

# Resize window
binde = $ctrlShift, H, resizeactive, -40 0
binde = $ctrlShift, L, resizeactive, 40 0
binde = $ctrlShift, K, resizeactive, 0 -40
binde = $ctrlShift, J, resizeactive, 0 40

# Move floating windows 
binde = $superShift, H, moveactive, -65 0
binde = $superShift, L, moveactive, 65 0
binde = $superShift, K, moveactive, 0 -65
binde = $superShift, J, moveactive, 0 65


# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Example special workspace (scratchpad)
# bind = $mainMod, S, togglespecialworkspace, magic

# Function keys
bindel = , XF86AudioRaiseVolume, exec, $ipc volume increase
bindel = , XF86AudioLowerVolume, exec, $ipc volume decrease
bindl = , XF86AudioMute, exec, $ipc volume muteOutput
bindel = , XF86MonBrightnessUp, exec, $ipc brightness increase
bindel = , XF86MonBrightnessDown, exec, $ipc brightness decrease
