#####################
### LOOK AND FEEL ###
#####################
general {
  gaps_in = 5
  gaps_out = 8
  gaps_out = 5, 8, 8, 8

  border_size = 2

  # col.active_border = rgba(abb2bfff)
  # col.inactive_border = rgba(1e212777)

  # Set to true enable resizing windows by clicking and dragging on borders and gaps
  resize_on_border = false

  # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
  allow_tearing = false

  # the current window layout
  layout = dwindle
}

decoration {
  rounding = 15
  rounding_power = 2

  active_opacity = 1.0
  inactive_opacity = 1.0

  shadow {
      enabled = true
      range = 6
      render_power = 3
      ignore_window = true
      # color = rgba(282c3444)
  }

  blur {
      enabled = true
      size = 5
      passes = 5
      new_optimizations = true
      xray = true

      vibrancy = 0.3
  }
}

animations {
  enabled = yes, please :)

  # Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
  #        NAME,           X0,   Y0,   X1,   Y1
  bezier = easeOutQuint,   0.23, 1,    0.32, 1
  bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
  bezier = linear,         0,    0,    1,    1
  bezier = almostLinear,   0.5,  0.5,  0.75, 1
  bezier = quick,          0.15, 0,    0.1,  1

  # Default animations, see https://wiki.hypr.land/Configuring/Animations/
  #           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
  animation = global,        1,     10,    default
  animation = border,        1,     5.5,  easeOutQuint
  animation = windows,       1,     4.8,  easeOutQuint
  animation = windowsOut,    1,     1.5,  linear,       popin 90%
  animation = fadeIn,        1,     1.8,  almostLinear
  animation = fadeOut,       1,     1.5,  almostLinear
  animation = fade,          1,     3,  quick
  animation = layers,        1,     3.8,  easeOutQuint
  animation = layersIn,      1,     5,     easeOutQuint, fade
  animation = layersOut,     1,     1.5,   linear,       fade
  animation = fadeLayersIn,  1,     1.8,  almostLinear
  animation = fadeLayersOut, 1,     1.5,  almostLinear
  animation = workspaces,    1,     1.8,  almostLinear, fade
  animation = workspacesIn,  1,     1.5,  almostLinear, fade
  animation = workspacesOut, 1,     1.8,  almostLinear, fade
  animation = zoomFactor,    1,     7,     quick
}


# Decoratino Layer/Window Rules
layerrule {
  name = noctalia
  match:namespace = noctalia-background-.*$
  ignore_alpha = 0.5
  blur = true
  blur_popups = true
}
