########################
###  MISC VARIABLES  ###
#######################

misc {
  force_default_wallpaper = false # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background
  # variable refresh rate settings
  vfr = true
  vrr = 1

  animate_manual_resizes = true
}

cursor { 
  no_hardware_cursors = true 
}

opengl {
  # reduces flickering, possible frame drops
  nvidia_anti_flicker = true
}

render { 
  # reduces lag when there is 1  full screen app
  direct_scanout = 1
}

