##############################
###     WINDOW LAYOUT      ###
##############################
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}


##############################
### WINDOWS AND WORKSPACES ###
##############################
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 10, monitor:eDP-1, default:true

windowrule {
    # Ignore maximize requests from all apps.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

##############################
###         MY RULES       ###
##############################
layerrule {
    name = rofi
    match:namespace =^(rofi)$
    dim_around = on
    animation = popin 80%
}

# floats file manager
windowrule {
  name = file-manager-float
  match:class = ^(thunar)$
  float = on
  center = on
  size = (window_w*1.2) (window_h*1.2)
}

# centers prompts/popups
windowrule {
  name = center-popups
  match:class = DesktopEditors
  float = on
  center = on
}

# blanket
windowrule {
  name = center-blanket
  match:class = com.rafaelmardojai.Blanket
  float = on
  center = on
  size = (window_w*1.5) (window_h*0.9)
}

# Application workspaces
windowrule = match:class ^(zen)$, workspace 1
windowrule = match:class ^(codium)$, workspace 2
windowrule = match:class ^(obsidian)$, workspace 3
windowrule = match:title ^(Blanket)$, workspace 6
